# Project Ambrose by Imjustchico
# Runs a built server executable to check that --version exits 0, a missing config names its path and exits 1, the shipped .conf.dist starts it, and that the login server updates and opens its database or exits 1 on a bad connection string.
if(NOT APP OR NOT NAME OR NOT WORKDIR)
    message(FATAL_ERROR "APP, NAME and WORKDIR must be set")
endif()

execute_process(COMMAND "${APP}" --version RESULT_VARIABLE versionResult OUTPUT_VARIABLE versionOutput ERROR_VARIABLE versionError TIMEOUT 30)
if(NOT versionResult EQUAL 0)
    message(FATAL_ERROR "${NAME} --version exited ${versionResult}: ${versionOutput}${versionError}")
endif()
if(NOT versionOutput MATCHES "Project Ambrose rev ")
    message(FATAL_ERROR "${NAME} --version printed '${versionOutput}'")
endif()

file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")
execute_process(COMMAND "${APP}" WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE missingResult OUTPUT_VARIABLE missingOutput ERROR_VARIABLE missingError TIMEOUT 30)
if(NOT missingResult EQUAL 1)
    message(FATAL_ERROR "${NAME} without a config exited ${missingResult}: ${missingOutput}${missingError}")
endif()
if(NOT missingError MATCHES "app-smoke[/\\\\]${NAME}[/\\\\]${NAME}\\.conf")
    message(FATAL_ERROR "${NAME} without a config did not name its full path: ${missingError}")
endif()
if(NOT missingError MATCHES "${NAME}\\.conf\\.dist")
    message(FATAL_ERROR "${NAME} without a config did not suggest copying ${NAME}.conf.dist: ${missingError}")
endif()

get_filename_component(appDir "${APP}" DIRECTORY)
set(portOption "${NAME}")
string(REPLACE "gameserver" "WorldServerPort" portOption "${portOption}")
string(REPLACE "loginserver" "LoginServerPort" portOption "${portOption}")
string(REPLACE "patchserver" "PatchServerPort" portOption "${portOption}")
set(quietOptions --set BindIP=127.0.0.1 --set ${portOption}=0 --set ClientDir= --set Appender.Server=1,3,0 --set Appender.Errors=1,3,0 --set Appender.Stream=1,3,0 --set Appender.Console=1,3,0)
execute_process(COMMAND "${APP}" --config "${appDir}/${NAME}.conf.dist" ${quietOptions} --set LoginDatabaseInfo= --set CharacterDatabaseInfo= --set WorldDatabaseInfo=
    WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE distResult OUTPUT_VARIABLE distOutput ERROR_VARIABLE distError TIMEOUT 5)
if(NOT distOutput MATCHES "${NAME} ready")
    message(FATAL_ERROR "${NAME} with its shipped ${NAME}.conf.dist did not report ready (${distResult}): ${distOutput}${distError}")
endif()

if(NAME STREQUAL "loginserver" AND DEFINED ENV{AMBROSE_TEST_DB} AND NOT "$ENV{AMBROSE_TEST_DB}" STREQUAL "")
    set(databaseParts "$ENV{AMBROSE_TEST_DB}")
    list(LENGTH databaseParts databasePartCount)
    if(databasePartCount GREATER_EQUAL 5)
        list(REMOVE_AT databaseParts 4)
        string(RANDOM LENGTH 8 ALPHABET "0123456789abcdef" smokeSuffix)
        list(INSERT databaseParts 4 "ambrose_smoke_login_${smokeSuffix}")
    endif()
    list(JOIN databaseParts ";" smokeDatabase)
    foreach(round IN ITEMS first second)
        execute_process(COMMAND "${APP}" --config "${appDir}/${NAME}.conf.dist" ${quietOptions} "--set=LoginDatabaseInfo=${smokeDatabase}"
            WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE databaseResult OUTPUT_VARIABLE databaseOutput ERROR_VARIABLE databaseError TIMEOUT 8)
        if(NOT databaseOutput MATCHES "Opened database connection pool login: 1 async, 1 sync" OR NOT databaseOutput MATCHES "loginserver ready")
            message(FATAL_ERROR "loginserver with AMBROSE_TEST_DB did not update, open the login pool and report ready on its ${round} start (${databaseResult}): ${databaseOutput}${databaseError}")
        endif()
        if(round STREQUAL "first" AND (NOT databaseOutput MATCHES "Created database ambrose_smoke_login_" OR NOT databaseOutput MATCHES "importing 2 base file" OR NOT databaseOutput MATCHES "Applied RELEASED 2026_01_01_00\\.sql to the login database"))
            message(FATAL_ERROR "loginserver's first start did not create the login database, import its base and apply its updates: ${databaseOutput}")
        endif()
    endforeach()
    if(NOT databaseOutput MATCHES "The login database is up to date")
        message(FATAL_ERROR "loginserver's second start did not report the login database up to date: ${databaseOutput}")
    endif()
endif()

if(NAME STREQUAL "loginserver")
    execute_process(COMMAND "${APP}" --config "${appDir}/${NAME}.conf.dist" ${quietOptions} "--set=LoginDatabaseInfo=not a connection string"
        WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE badResult OUTPUT_VARIABLE badOutput ERROR_VARIABLE badError TIMEOUT 30)
    if(NOT badResult EQUAL 1)
        message(FATAL_ERROR "loginserver with a bad LoginDatabaseInfo exited ${badResult}: ${badOutput}${badError}")
    endif()
    if(NOT badOutput MATCHES "LoginDatabaseInfo is not a valid connection string")
        message(FATAL_ERROR "loginserver with a bad LoginDatabaseInfo did not explain why: ${badOutput}${badError}")
    endif()
endif()
