# Project Ambrose by Imjustchico
# Runs bindecode to check its usage text, that bad usage exits 2 and a missing archive named by path exits 1 before anything is searched, that on a machine holding a synthetic install AMBROSE_SETUP_MODE=off prints the find and the flag to pass while auto uses it and reports why no type dump could be built from it, and, when AMBROSE_CLIENT_DIR and AMBROSE_TYPE_DUMP_PATH name the user's own install and type dump, that it lists a crown hat, prints that hat as JSON with its template id and display name, and exits 1 for an entry that does not exist; it reports itself skipped when the client checks cannot run.
if(NOT APP OR NOT WORKDIR)
    message(FATAL_ERROR "APP and WORKDIR must be set")
endif()
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")

execute_process(COMMAND "${APP}" --help RESULT_VARIABLE helpResult OUTPUT_VARIABLE helpOutput ERROR_VARIABLE helpError TIMEOUT 30)
if(NOT helpResult EQUAL 0 OR NOT helpOutput MATCHES "Usage: bindecode" OR NOT helpOutput MATCHES "--sweep")
    message(FATAL_ERROR "bindecode --help exited ${helpResult}: ${helpOutput}${helpError}")
endif()

foreach(arguments IN ITEMS "" "--list;--sweep" "--sweep;Entry.xml" "--threads;0;--sweep" "--bogus")
    execute_process(COMMAND "${APP}" ${arguments} RESULT_VARIABLE usageResult OUTPUT_VARIABLE usageOutput ERROR_VARIABLE usageError TIMEOUT 30)
    if(NOT usageResult EQUAL 2 OR NOT usageError MATCHES "bindecode: .*Usage: bindecode")
        message(FATAL_ERROR "bindecode with arguments '${arguments}' exited ${usageResult} instead of 2: ${usageOutput}${usageError}")
    endif()
endforeach()

set(machine "${WORKDIR}/machine")
set(synthetic "${machine}/drive_c/ProgramData/KingsIsle Entertainment/Wizard101")
file(WRITE "${synthetic}/Data/GameData/Root.wad" "not an archive")
file(WRITE "${synthetic}/Bin/revision.dat" "r999999999.Synthetic_1_0\n")
set(machineEnv "ProgramData=${machine}/drive_c/ProgramData" "WINEPREFIX=${machine}" "LOCALAPPDATA=${WORKDIR}/data" "XDG_DATA_HOME=${WORKDIR}/data" --unset=AMBROSE_CLIENT_DIR --unset=AMBROSE_TYPE_DUMP_PATH --unset=AMBROSE_WORLD_DATABASE_INFO)
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${machineEnv} AMBROSE_SETUP_MODE=auto "${APP}" --wad "${WORKDIR}/missing.wad" Entry.xml RESULT_VARIABLE missingResult OUTPUT_VARIABLE missingOutput ERROR_VARIABLE missingError TIMEOUT 30)
if(NOT missingResult EQUAL 1 OR NOT missingError MATCHES "cannot open .*missing\.wad" OR missingError MATCHES "found on this machine|bindecode: using|type dump")
    message(FATAL_ERROR "bindecode with a missing archive searched the machine or exited ${missingResult}: ${missingOutput}${missingError}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${machineEnv} AMBROSE_SETUP_MODE=off "${APP}" Entry.xml RESULT_VARIABLE offResult OUTPUT_VARIABLE offOutput ERROR_VARIABLE offError TIMEOUT 30)
if(NOT offResult EQUAL 1 OR NOT offError MATCHES "bindecode: Wizard101 was found on this machine: [^\n]*r999999999\\.Synthetic_1_0" OR NOT offError MATCHES "Pass --client with one of them, or set AMBROSE_SETUP_MODE=auto to use the newest")
    message(FATAL_ERROR "bindecode with AMBROSE_SETUP_MODE=off did not print the install it found and the flag to pass (${offResult}): ${offOutput}${offError}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${machineEnv} AMBROSE_SETUP_MODE=auto "${APP}" Entry.xml RESULT_VARIABLE autoResult OUTPUT_VARIABLE autoOutput ERROR_VARIABLE autoError TIMEOUT 60)
if(NOT autoResult EQUAL 1 OR NOT autoError MATCHES "bindecode: cannot build the type dump for [^\n]*r999999999\\.Synthetic_1_0" OR NOT autoError MATCHES "bindecode: using the newest install on this machine, [^\n]*r999999999\\.Synthetic_1_0[^\n]*; pass --client to choose otherwise")
    message(FATAL_ERROR "bindecode with AMBROSE_SETUP_MODE=auto did not use the synthetic install and report the type dump it could not build (${autoResult}): ${autoOutput}${autoError}")
endif()

if("$ENV{AMBROSE_CLIENT_DIR}" STREQUAL "" OR "$ENV{AMBROSE_TYPE_DUMP_PATH}" STREQUAL "")
    message(STATUS "bindecode test skipped: its client checks need AMBROSE_CLIENT_DIR and AMBROSE_TYPE_DUMP_PATH")
    return()
endif()
set(hat "ObjectData/CrownItems/Series58/Hats/Crowns-S58-Hats-L110-BS-008-01.xml")
execute_process(COMMAND "${APP}" --list Crowns-S58-Hats-L110-BS-008 RESULT_VARIABLE listResult OUTPUT_VARIABLE listOutput ERROR_VARIABLE listError TIMEOUT 120)
if(NOT listResult EQUAL 0 OR NOT listOutput MATCHES "Crowns-S58-Hats-L110-BS-008-01\.xml")
    message(FATAL_ERROR "bindecode --list exited ${listResult}: ${listOutput}${listError}")
endif()
execute_process(COMMAND "${APP}" --compact "${hat}" RESULT_VARIABLE hatResult OUTPUT_VARIABLE hatOutput ERROR_VARIABLE hatError TIMEOUT 300)
if(NOT hatResult EQUAL 0 OR NOT hatOutput MATCHES "^{\"[$]class\":\"class WizItemTemplate\"" OR NOT hatOutput MATCHES "\"m_templateID\":1652259" OR NOT hatOutput MATCHES "\"m_displayName\":\"Items_00028316\"")
    message(FATAL_ERROR "bindecode did not print the crown hat (${hatResult}): ${hatOutput}${hatError}")
endif()
execute_process(COMMAND "${APP}" No/Such/Entry.xml RESULT_VARIABLE absentResult OUTPUT_VARIABLE absentOutput ERROR_VARIABLE absentError TIMEOUT 300)
if(NOT absentResult EQUAL 1 OR NOT absentError MATCHES "No/Such/Entry\.xml: ")
    message(FATAL_ERROR "bindecode with an entry that does not exist exited ${absentResult}: ${absentOutput}${absentError}")
endif()
