# Project Ambrose by Imjustchico
# Run by ambrose_embed_page with cmake -P: lists FOLDER, and when its files, sizes or times differ from the last run writes SOURCE and HEADER holding each file as bytes with its path, media type, entity tag and whether it is a hashed asset under assets/, or a placeholder index.html naming PLACEHOLDER when the folder holds no built page.
cmake_minimum_required(VERSION 3.25)

function(media_type file out)
    get_filename_component(extension "${file}" LAST_EXT)
    string(TOLOWER "${extension}" extension)
    set(text "")
    if(extension STREQUAL ".html")
        set(result "text/html")
        set(text "; charset=utf-8")
    elseif(extension STREQUAL ".js" OR extension STREQUAL ".mjs")
        set(result "text/javascript")
        set(text "; charset=utf-8")
    elseif(extension STREQUAL ".css")
        set(result "text/css")
        set(text "; charset=utf-8")
    elseif(extension STREQUAL ".txt")
        set(result "text/plain")
        set(text "; charset=utf-8")
    elseif(extension STREQUAL ".json" OR extension STREQUAL ".map")
        set(result "application/json")
    elseif(extension STREQUAL ".webmanifest")
        set(result "application/manifest+json")
    elseif(extension STREQUAL ".svg")
        set(result "image/svg+xml")
    elseif(extension STREQUAL ".png")
        set(result "image/png")
    elseif(extension STREQUAL ".webp")
        set(result "image/webp")
    elseif(extension STREQUAL ".ico")
        set(result "image/x-icon")
    elseif(extension STREQUAL ".woff2")
        set(result "font/woff2")
    else()
        set(result "application/octet-stream")
    endif()
    set(${out} "${result}${text}" PARENT_SCOPE)
endfunction()

set(files)
if(EXISTS "${FOLDER}/index.html")
    file(GLOB_RECURSE files RELATIVE "${FOLDER}" "${FOLDER}/*")
    list(SORT files)
endif()

set(signature "${NAME}|${PLACEHOLDER}")
foreach(file IN LISTS files)
    file(SIZE "${FOLDER}/${file}" size)
    file(TIMESTAMP "${FOLDER}/${file}" stamp "%s" UTC)
    string(APPEND signature "|${file}:${size}:${stamp}")
endforeach()
string(SHA256 signature "${signature}")
set(stamp_file "${SOURCE}.stamp")
if(EXISTS "${SOURCE}" AND EXISTS "${HEADER}" AND EXISTS "${stamp_file}")
    file(READ "${stamp_file}" previous)
    if(previous STREQUAL signature)
        return()
    endif()
endif()

set(scratch "${SOURCE}.part")
file(WRITE "${scratch}" "#include \"${NAME}.h\"\n\nnamespace\n{\n")
set(entries "")
set(placeholder false)
if(NOT files)
    set(placeholder true)
    set(text "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>Ambrose</title></head><body><p>${PLACEHOLDER}</p></body></html>")
    string(HEX "${text}" hex)
    string(LENGTH "${text}" length)
    string(SHA256 digest "${text}")
    set(files index.html)
    set(placeholder_hex "${hex}")
endif()

set(index 0)
foreach(file IN LISTS files)
    if(placeholder)
        set(hex "${placeholder_hex}")
        string(SHA256 digest "${text}")
    else()
        file(READ "${FOLDER}/${file}" hex HEX)
        file(SHA256 "${FOLDER}/${file}" digest)
    endif()
    string(LENGTH "${hex}" hex_length)
    math(EXPR length "${hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,)(0x..,))" "\\1\n" bytes "${bytes}")
    if(length EQUAL 0)
        set(bytes "0x00,")
    endif()
    file(APPEND "${scratch}" "    unsigned char const File${index}[] = {\n${bytes}\n};\n")
    media_type("${file}" type)
    string(SUBSTRING "${digest}" 0 16 tag)
    if(file MATCHES "^assets/")
        set(hashed true)
    else()
        set(hashed false)
    endif()
    string(APPEND entries "        EmbeddedFile{ \"${file}\", \"${type}\", \"\\\"${tag}\\\"\", std::string_view(reinterpret_cast<char const*>(File${index}), ${length}), ${hashed} },\n")
    math(EXPR index "${index} + 1")
endforeach()

file(APPEND "${scratch}" "\n    EmbeddedFile const Files[] = {\n${entries}    };\n}\n\nEmbeddedPage const& ${NAME}()\n{\n    static EmbeddedPage const page(Files, ${placeholder});\n    return page;\n}\n")
file(WRITE "${HEADER}.part" "#ifndef AMBROSE_EMBEDDED_${NAME}_H\n#define AMBROSE_EMBEDDED_${NAME}_H\n\n#include \"EmbeddedPage.h\"\n\nEmbeddedPage const& ${NAME}();\n\n#endif\n")
file(RENAME "${scratch}" "${SOURCE}")
file(RENAME "${HEADER}.part" "${HEADER}")
file(WRITE "${stamp_file}" "${signature}")
