# Project Ambrose by Imjustchico
# Runs shell_smoke: copies it with its libraries into a folder the user is then denied writing to, made immutable where a superuser ignores its permissions, opens the launcher's page from memory from there and checks the folder holds exactly what it did before, then runs its remote-origin checks against loopback listeners and its pin checks against two certificates written by supervisor --panel-self-signed; it reports itself skipped when this machine has no web view.
if(NOT SMOKE OR NOT WORKDIR)
    message(FATAL_ERROR "SMOKE and WORKDIR must be set")
endif()

function(allow_writing folder)
    if(NOT EXISTS "${folder}")
        return()
    endif()
    if(WIN32)
        execute_process(COMMAND icacls "${folder}" /remove:d *S-1-1-0 /T /C /Q OUTPUT_QUIET ERROR_QUIET)
    else()
        execute_process(COMMAND chattr -i "${folder}" OUTPUT_QUIET ERROR_QUIET)
        execute_process(COMMAND chmod -R u+w "${folder}" OUTPUT_QUIET ERROR_QUIET)
    endif()
endfunction()

function(run_smoke label)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 300)
    if(output MATCHES "shell smoke skipped")
        allow_writing("${WORKDIR}/readonly")
        message(STATUS "shell smoke skipped: this machine has no web view")
        return()
    endif()
    if(NOT result EQUAL 0)
        allow_writing("${WORKDIR}/readonly")
        message(FATAL_ERROR "shell_smoke ${label} exited ${result}:\n${output}${error}")
    endif()
    message(STATUS "shell_smoke ${label}:\n${output}")
endfunction()

function(list_folder folder out)
    file(GLOB_RECURSE found LIST_DIRECTORIES true RELATIVE "${folder}" "${folder}/*")
    list(SORT found)
    set(${out} "${found}" PARENT_SCOPE)
endfunction()

allow_writing("${WORKDIR}/readonly")
file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}/readonly")

execute_process(COMMAND "${SMOKE}" available RESULT_VARIABLE probeResult OUTPUT_VARIABLE probeOutput ERROR_VARIABLE probeError TIMEOUT 60)
if(probeOutput MATCHES "shell smoke skipped")
    message(STATUS "shell smoke skipped: this machine has no web view")
    return()
endif()

get_filename_component(smokeName "${SMOKE}" NAME)
file(COPY "${SMOKE}" DESTINATION "${WORKDIR}/readonly")
string(REPLACE "|" ";" libraries "${DLLS}")
foreach(library IN LISTS libraries)
    if(library)
        file(COPY "${library}" DESTINATION "${WORKDIR}/readonly")
    endif()
endforeach()
list_folder("${WORKDIR}/readonly" before)

if(WIN32)
    execute_process(COMMAND icacls "${WORKDIR}/readonly" /deny "*S-1-1-0:(W,DC)" /C /Q RESULT_VARIABLE denied OUTPUT_VARIABLE deniedOutput ERROR_VARIABLE deniedError)
else()
    execute_process(COMMAND chmod -R a-w "${WORKDIR}/readonly" RESULT_VARIABLE denied OUTPUT_VARIABLE deniedOutput ERROR_VARIABLE deniedError)
endif()
if(NOT denied EQUAL 0)
    message(FATAL_ERROR "the smoke folder could not be made read-only: ${deniedOutput}${deniedError}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E touch "${WORKDIR}/readonly/written" RESULT_VARIABLE touched OUTPUT_QUIET ERROR_QUIET)
if(touched EQUAL 0 AND NOT WIN32)
    file(REMOVE "${WORKDIR}/readonly/written")
    execute_process(COMMAND chattr +i "${WORKDIR}/readonly" OUTPUT_QUIET ERROR_QUIET)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E touch "${WORKDIR}/readonly/written" RESULT_VARIABLE touched OUTPUT_QUIET ERROR_QUIET)
endif()
if(touched EQUAL 0)
    allow_writing("${WORKDIR}/readonly")
    message(FATAL_ERROR "the smoke folder still takes a new file after it was made read-only")
endif()

run_smoke("own, from a folder the user cannot write" "${WORKDIR}/readonly/${smokeName}" own "${WORKDIR}/own-data")
allow_writing("${WORKDIR}/readonly")
list_folder("${WORKDIR}/readonly" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "the window's run wrote beside the executable:\nbefore: ${before}\nafter: ${after}")
endif()
if(EXISTS "${WORKDIR}/own-data/Launcher/webview/own")
    message(STATUS "the web view kept its data in ${WORKDIR}/own-data/Launcher/webview/own")
else()
    message(FATAL_ERROR "the web view kept no data under the launcher's own data folder")
endif()

run_smoke("remote" "${SMOKE}" remote "${WORKDIR}/remote")

if(NOT SUPERVISOR)
    message(STATUS "shell smoke: the pin checks need the supervisor to write their certificates, and this build has none")
    return()
endif()
foreach(index IN ITEMS 1 2)
    set(conf "${WORKDIR}/certificate-${index}.conf")
    file(WRITE "${conf}" "Panel.CertificateFile = \"${WORKDIR}/certificate-${index}.pem\"\nPanel.PrivateKeyFile = \"${WORKDIR}/key-${index}.pem\"\n")
    execute_process(COMMAND "${SUPERVISOR}" --panel-self-signed --config "${conf}" RESULT_VARIABLE written OUTPUT_VARIABLE writtenOutput ERROR_VARIABLE writtenError TIMEOUT 60)
    if(NOT written EQUAL 0)
        message(FATAL_ERROR "supervisor --panel-self-signed exited ${written}: ${writtenOutput}${writtenError}")
    endif()
endforeach()
run_smoke("pin" "${SMOKE}" pin "${WORKDIR}/pin" "${WORKDIR}/certificate-1.pem" "${WORKDIR}/key-1.pem" "${WORKDIR}/certificate-2.pem" "${WORKDIR}/key-2.pem")
