/*
 * Project Ambrose by Imjustchico
 * Tests the reader of the client's DML table XML on a document shaped like AnimationData/MasterAnimationList.xml: a byte order mark, declaration and comment before the root, every table its _TableList names read in order with each record's fields, their types, which is the key and their text, an empty table read as empty and a table looked up by name; and a document that is not XML, has no _TableList or lists a table it does not hold refused with the reason.
 */

#include "DmlTableFile.h"

#include <gtest/gtest.h>

#include <string>

namespace
{
    constexpr char const* Animations = "\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
                                       "<MasterAnimationList>\n"
                                       "  <!--Warning: Generated by Kobol - changes to this file may be overwritten-->\n"
                                       "  <_TableList>\n"
                                       "    <RECORD><Name TYPE=\"STR\">Animations</Name></RECORD>\n"
                                       "    <RECORD><Name TYPE=\"STR\">SkeletonMovement</Name></RECORD>\n"
                                       "  </_TableList>\n"
                                       "  <Animations>\n"
                                       "    <RECORD>\n"
                                       "      <AnimType KEY=\"TRUE\" TYPE=\"STR\">Wave</AnimType>\n"
                                       "      <NumAnims TYPE=\"INT\">1</NumAnims>\n"
                                       "      <Animation0 TYPE=\"UINT\">205</Animation0>\n"
                                       "    </RECORD>\n"
                                       "    <RECORD><AnimType KEY=\"TRUE\" TYPE=\"STR\">Chat</AnimType></RECORD>\n"
                                       "  </Animations>\n"
                                       "  <SkeletonMovement>\n"
                                       "  </SkeletonMovement>\n"
                                       "</MasterAnimationList>\n";
}

TEST(DmlTableFileTest, EveryListedTableIsReadWithItsRecordsAndFields)
{
    std::string error;
    std::optional<std::vector<DmlTable>> const tables = DmlTableFile::Parse(Animations, error);
    ASSERT_TRUE(tables) << error;
    ASSERT_EQ(tables->size(), 2u);
    EXPECT_EQ((*tables)[0].Name, "Animations");
    EXPECT_EQ((*tables)[1].Name, "SkeletonMovement");
    EXPECT_TRUE((*tables)[1].Records.empty());

    DmlTable const* const animations = DmlTableFile::Find(*tables, "Animations");
    ASSERT_NE(animations, nullptr);
    ASSERT_EQ(animations->Records.size(), 2u);
    DmlTableRecord const& wave = animations->Records[0];
    ASSERT_EQ(wave.Fields.size(), 3u);
    DmlTableField const* const type = wave.Find("AnimType");
    ASSERT_NE(type, nullptr);
    EXPECT_TRUE(type->Key);
    EXPECT_EQ(type->Type, "STR");
    EXPECT_EQ(type->Value, "Wave");
    DmlTableField const* const count = wave.Find("NumAnims");
    ASSERT_NE(count, nullptr);
    EXPECT_FALSE(count->Key);
    EXPECT_EQ(count->Type, "INT");
    EXPECT_EQ(count->Value, "1");
    EXPECT_EQ(wave.Find("Animation0")->Value, "205");
    EXPECT_EQ(wave.Find("Missing"), nullptr);
    EXPECT_EQ(animations->Records[1].Find("AnimType")->Value, "Chat");
    EXPECT_EQ(DmlTableFile::Find(*tables, "Nowhere"), nullptr);
}

TEST(DmlTableFileTest, ADocumentThatIsNotSuchXmlOrListsATableItLacksIsRefused)
{
    std::string error;
    EXPECT_FALSE(DmlTableFile::Parse("<Root><_TableList>", error));
    EXPECT_NE(error.find("is not well-formed XML"), std::string::npos) << error;
    EXPECT_FALSE(DmlTableFile::Parse("<Root><Animations/></Root>", error));
    EXPECT_NE(error.find("has no _TableList under its root element <Root>"), std::string::npos) << error;
    EXPECT_FALSE(DmlTableFile::Parse("<Root><_TableList><RECORD><Name TYPE=\"STR\">Animations</Name></RECORD></_TableList></Root>", error));
    EXPECT_NE(error.find("lists the table 'Animations', which it does not hold"), std::string::npos) << error;
}
